.PHONY:build
build:
	echo "building.."
	go build -o bin/auth-api ./cmd/service/main.go

.PHONY:run
run:
	echo "running.."
	go run -race ./cmd/service/main.go

.PHONY:test
test:
	echo "testing.."
	go clean -testcache
	go test -v -cover -tags=entities ./...

.DEFAULT_GOAL := run