version: "3.5"

volumes:
  database_data:
    driver: local

services:
  db:
    image: postgres:latest
    ports:
      - "5433:5432"
    volumes:
      - database_data:/var/lib/postgresql/data

  cache:
    image: redis:latest
    ports:
      - "6379:6379"

  service-teams:
    image: service-teams
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "50051:50051"
    environment:
      - PORT=50051
      - CONNECTION_STRING=host=db port=5432 user=postgres password=postgres dbname=service_teams sslmode=disable
    depends_on:
      - db
      - cache